version: '3.7'
services:
  watcher:
    build: .
    restart: always
    entrypoint: ["/transcode", "watcher"]
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./example:/data

  splitter:
    build: .
    restart: always
    entrypoint: ["/transcode", "splitter"]
    depends_on:
      - rabbitmq
    volumes:
      - ./example:/data

  encoder:
    build: .
    restart: always
    entrypoint: ["/transcode", "encoder"]
    depends_on:
      - rabbitmq
    volumes:
      - ./example:/data

  merger:
    build: .
    restart: always
    entrypoint: ["/transcode", "merger"]
    depends_on:
      - rabbitmq
    volumes:
      - ./example:/data

  packager:
    build: .
    restart: always
    entrypoint: ["/transcode", "packager"]
    depends_on:
      - rabbitmq
    volumes:
      - ./example:/data

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    ports:
      - 9999:9999

  telegraf:
    image: telegraf
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000